"""
REQUIRMENTS
Adafruit_DHT, MYSQL, PYMYSQL, savetoDB.py


GPIO SETTINGS
02(DC 5V)   (LOADCELL DC, Adafruit_DHT.DHT11 DC, RELAY DC) -> NEED GPIO DISTRIBUTER!!
04(DC 5V)   RSP FAN DC
06(GND)     RSP FAN GND
30(GND)     RELAY GND
29(GPIO05)  RELAY INPUT1 (LAMP)
31(GPIO06)  RELAY INPUT4 (BLANKET)
33(GPIO13)  RELAY INPUT3 (HUMIDITY)
34(GND)     LOADCELL GND
36(GPIO16)  LOADCELL SCK
38(GPIO20)  LOADCELL DT
39(GND)     Adafruit_DHT.DHT11 GND
40(GPIO21)  Adafruit_DHT.DHT11 DT
"""

#BLANKET ON
import RPi.GPIO as GPIO
import time

GPIO.setmode(GPIO.BCM)
GPIO.setup(6,GPIO.OUT)

GPIO.output(6,False)
